### ISSUE TITLE
Rip out `launch` that assumes root or current user context?

### ISSUE THREAD

**Issue by joshgoebel** [joshgoebel/keyszer#12]
- Does launch make sense when running as a privileged (non-root) user?  
- How would you run commands as the current user?  
- Or does it only make sense when running yourself as a slightly elevated-user with access to input devices?  
- Should we even support this latter config (running as the current user) as it could allow malicious software to easily log all keystrokes?

**Comment by RedBearAK** [comment]
@joshgoebel 

Can't really answer the security questions, but I've got my `xkeysnail` on my daily driver set up to run as user rather than root, and it really simplified my `launch` commands. I've set up a number of `launch` commands for various purposes: 

```
# Keybindings overrides for Nautilus
# (overrides some bindings from general file manager code block below)
define_keymap(re.compile("org.gnome.nautilus|nautilus", re.IGNORECASE),{
    K("RC-N"):          launch(["nautilus", "--new-window", _cwd]),     # Open default file manager at home folder
...
define_keymap(re.compile(termStr, re.IGNORECASE),{
    K("Shift-LC-RC-M-k"):   launch(["/usr/local/bin/stop_xkeysnail.sh"]),       # try to stop Kinto (xkeysnail) process
},"Magic shortcut to kill Kinto")
...
# None referenced here originally
# - but remote clients and VM software ought to be set here
# These are the typical remaps for ALL GUI based apps
define_keymap(lambda wm_class: wm_class.casefold() not in remotes,{
    K("Shift-Super-RC-M-k"):    launch(["/usr/local/bin/stop_xkeysnail.sh"]),          # try to stop Kinto (xkeysnail) process
...
    K("RC-Shift-M-l"):      [launch_and_then(["gedit"], sleep_and_then(3, [K("Enter"), K("t"), K("e"), K("x"), K("t"), K("Enter")]))],
    K("RC-Shift-M-b"):      launch([_kintopath + "play_sound.py", "error"]),         # launch beepy error beep
    K("RC-Shift-KEY_3"):    launch([_kintopath + "screenshot.sh", "desktop"]),       # Cmd+Shift+3       # screenshot: entire desktop (all attached displays, macOS default)
    K("M-RC-Shift-KEY_3"):  launch([_kintopath + "screenshot.sh", "screen"]),        # Opt+Cmd+Shift+3   # screenshot: screen with focus
    K("RC-Shift-KEY_4"):    launch([_kintopath + "screenshot.sh", "area"]),          # Cmd+Shift+4       # screenshot: select area
    K("M-RC-Shift-KEY_4"):  launch([_kintopath + "screenshot.sh", "window"]),        # Opt+Cmd+Shift+4   # screenshot: window with focus
    K("RC-Shift-KEY_5"):    launch([_kintopath + "screenshot.sh", "show-app"]),      # Cmd+Shift+5       # screenshot: show screenshot tool (app)
    K("M-RC-Shift-KEY_5"):  launch([_kintopath + "screenshot.sh", "config"]),        # Opt+Cmd+Shift+5   # open screenshot config file
    K("M-RC-Space"):        launch(["/usr/bin/xdg-open", _cwd]),                         # Open default file manager at home folder
...
```

I would very much like to see a number of improvements to `launch` and `sleep`. One big thing that threw me was that I couldn't do `launch` or `sleep` easily as part of a macro. A user on the main `xkeysnail` forums (Lenbok) offered some alternate functions that I have pasted in my Kinto config file, just for testing: 

```
def launch_and_then(command, next):
    """Launch command"""
    def launcher():
        from subprocess import Popen
        Popen(command)
        return next
    return launcher

def sleep_and_then(sec, next):
    """Sleep sec in commands"""
    def sleeper():
        import time
        time.sleep(sec)
        return next
    return sleeper
```

Before I forget, the other thing about `launch` that I would like to see fixed is that if you get things even slightly wrong it will.... not exactly crash `xkeysnail`, but something very odd happens, particularly to the task switcher dialog. It's very unstable/sensitive to perfect syntax. That gave me a lot of trouble when testing `launch` commands. I wish the command would just fail with an error, but not mess up the whole functioning of `xkeysnail`.

**Comment by joshgoebel** [comment]
>but I've got my xkeysnail on my daily driver set up to run as user rather than root

That's the only time I think `launch` makes some sense, but then you're left with the problem of ANY software on  your computer having completely access to read EVERY keystroke, see your passwords (as you type them), etc... not sure we want to encourage that.

Also there are a LOT of  "listen for key, run program" programs out there... I wonder if those are incompatible with us or if they could be used on top just fine... is there something about launching we do BETTER other than just being easy/convenient?

> def sleep_and_then(sec, next):

I'm VERY uncomfortable with this (sleep in general)... This can freeze ALL input... imagine someone is ALSO routing a smart mouse thru to remap some of the keys (or their keyboard and trackpad are a single device)... now when you sleep for 3 seconds you break the mouse from moving, etc... 

I think of key mapping as VERY low-level in nature (almost kernel like).... it's not something that should ever just PAUSE, not ever, it should be as fast as possible.  launch and sleep kind of both go against that thinking.

**Comment by joshgoebel** [comment]
> if you get things even slightly wrong it will..

If you're just talking about how you have to have a function return a function, that's just how it works... the fact is when writing actual code inside the mapper it's very easy to break the mapper... requires much care.  If there is something else specific I'd need to be pointer to it.

**Comment by joshgoebel** [comment]
Take this:

```
[launch_and_then(["gedit"], sleep_and_then(3, [K("Enter"), K("t"), K("e"), K("x"), K("t"), K("Enter")]))],
```

Also there are many different ways this could go bad... you can't know for certain gedit will launch - that it won't launch in some error state - or that you'll be typing those keystrokes into the right window...  that "Enter" your sending could be confirming "Do you want to delete all files?" or something... sending input blindly (after a long delay and depending on external processes) is just **scary**.

I have no plans to remove the "run python code" functionality, so sleep and launch could always be "use at your own risk" features where someone just pastes in the code into their config - but so far I don't see any great reasons to be encourage these (unless the safety and reliability could somehow be much improved).

**Comment by RedBearAK** [comment]
@joshgoebel 

>I think of key mapping as VERY low-level in nature (almost kernel like).... it's not something that should ever just PAUSE, not ever, it should be as fast as possible. launch and sleep kind of both go against that thinking.

This definitely sounds like something that should be external to the main remapper functions, or at least in a different thread or something, if it's so dangerous, and can interrupt all input like that. 

>There are SO many different ways this could go bad...

Yes, all good points, of course. 

I was just playing around with the Gedit thing, to see what I could get working. But there are various situations where a bit of automation can come in very handy. Certainly the ability to recognize when you're actually in the target window would be... recommended. 

One of the useful things `launch` did for me was letting me force new Nautilus file browser windows opened with Cmd+N to open in my home folder instead of the same folder as the last Nautilus window to have focus. But even then it requires a variable to grab the user's home path (or you have to hard code the user's home path in the config file). 

```
# needs "import os"
_cwd = os.getcwd()
```

The other shortcut, to open a default file browser window with Opt+Cmd+Space, could just as easily be set up in the DE's keyboard shortcut config. 

```
    K("M-RC-Space"):        launch(["/usr/bin/xdg-open", _cwd]),                         # Open default file manager at home folder
```

The lines below let me mimic the way screenshot shortcuts work in macOS, using an external script in the Kinto config directory. It looks for available screenshot tools and does the action corresponding to the shortcut. 

```
    K("RC-Shift-KEY_3"):    launch([_kintopath + "screenshot.sh", "desktop"]),       # Cmd+Shift+3       # screenshot: entire desktop (all attached displays, macOS default)
    K("M-RC-Shift-KEY_3"):  launch([_kintopath + "screenshot.sh", "screen"]),        # Opt+Cmd+Shift+3   # screenshot: screen with focus
    K("RC-Shift-KEY_4"):    launch([_kintopath + "screenshot.sh", "area"]),          # Cmd+Shift+4       # screenshot: select area
    K("M-RC-Shift-KEY_4"):  launch([_kintopath + "screenshot.sh", "window"]),        # Opt+Cmd+Shift+4   # screenshot: window with focus
    K("RC-Shift-KEY_5"):    launch([_kintopath + "screenshot.sh", "show-app"]),      # Cmd+Shift+5       # screenshot: show screenshot tool (app)
    K("M-RC-Shift-KEY_5"):  launch([_kintopath + "screenshot.sh", "config"]),        # Opt+Cmd+Shift+5   # open screenshot config file
```

It would certainly be possible to set up individual system shortcuts for all these in the DE keyboard shortcuts dialog, but it would be tedious. With `xkeysnail` running as user and this script in the Kinto directory, this would just automagically work on any system that had GNOME Screenshot, Spectacle or Flameshot installed. 

The script: https://github.com/rbreaves/kinto/issues/604

I also wanted to mimic the way the Finder gives a "beep" error when you try to use Delete or Backspace without the Cmd key. 

```
    K("RC-Shift-M-b"):      launch([_kintopath + "play_sound.py", "error"]),         # launch beepy error beep
```

The script to play a sound: https://github.com/rbreaves/kinto/issues/615

>If you're just talking about how you have to have a function return a function, that's just how it works... the fact is when writing actual code inside the mapper it's very easy to break the mapper... requires much care. If there is something else specific I'd need to be pointer to it.

I'm just talking about how the `launch` function doesn't seem to do well handling errors in the actual command it's trying to run. Shouldn't it be able to catch and properly deal with an error state, without messing up the entire application? Something like python's `try`? And just send something to the log if the shell command had some sort of error? Instead it seems to put `xkeysnail` into a really weird state and I have to kill it, fix the failing `launch` line and restart it. A couple of times this could have left me in a bad situation (requiring hard reboot or sshing in to restart) if I hadn't still had a way to kill the process from a dock icon or the tray icon. 

I'm open to suggestions for using other applications to do this kind of automation.

**Comment by joshgoebel** [comment]
> I also wanted to mimic the way the Finder gives a "beep" error when you try to use Delete or Backspace without the Cmd key.

This  is problematic to as this depends on WAY more than just which app is focused... maybe it's cute if you're looking at a folder (and focused on a file), but it's far less cute if you're inside the preferences dialog and hitting backspace over and over to delete something to change a preference.  Perhaps this is a little bit saner if paired with WM_NAME though, would depend on the app.

A low-level keymapper just isn't the right place to add these contextual things, IMHO.

> I'm just talking about how the launch function doesn't seem to do well handling errors in the actual command it's trying to run. Shouldn't it be able to catch and properly deal with an error state, without messing up the entire application?

Sure, but to help I'd need a specific re-producable example case... and users having to dig into their keymapper logs to see why a process didn't launch also doesn't sound super appealing. :)

> I'm open to suggestions for using other applications to do this kind of automation.

Sxhkd is popular I think: https://wiki.archlinux.org/title/Sxhkd  

I do this kind of stuff in Awesome (my Window Manager).

**Comment by RedBearAK** [comment]
>This is problematic to as this depends on WAY more than just which app is focused... maybe it's cute if you're looking at a folder (and focused on a file), but it's far less cute if you're inside the preferences dialog and hitting backspace over and over to delete something to change a preference. Perhaps this is a little bit saner if paired with WM_NAME though, would depend on the app.

All very, very true, I think we can agree. And the reason that I actually ended up retracting my PR to Kinto. LOL. Because it was a dumb idea and makes no sense unless you're actually in the file/folder pane. 

AutoHotKey on the Windows side has the ability to detect which part of the window you're in, so it has a better ability to deal with things like this. But it's also exceedingly complex to work with. 

You might notice the beep shortcut is Ctrl+Shift+Alt+b. I was actually just using it for testing the beep. LOL. 

> A low-level keymapper just isn't the right place to add these contextual things, IMHO.

Perhaps not. I did bring a lot of Finder shortcuts into Kinto's config. The whole section on file managers is mine. But those were still just normal shortcuts. Using `launch` and the external script was the only way I could figure out to add the screenshot shortcuts functionally into Kinto in a sort-of portable way. But the `launch` commands are more complex and require `runuser` and a hard coded username to work when the app is running as root. 

>Sxhkd is popular I think

I'll check that out, and any alternatives I can find.

**Comment by joshgoebel** [comment]
> But the launch commands are more complex and require runuser and a hard coded username to work when the app is running as root.

Yeah, but I want to get away entirely from running as root... and once you're running not as root and ALSO not as the current user (for security) then launching things becomes much less useful.

**Comment by joshgoebel** [comment]
I'm truly interested here in the best argument someone has for why we shouldn't (by default) care about  letting any software a user runs potentially become a keylogger because the user has been given that permission (access to raw input devices).

_Where I'm at right now:_

I'm leaning towards ripping this functionality out... and looking for a better, safer way to add it back (with a separate client), something like #44 for a minimal proposal.

If a user REALLY wants to do this they could (by just manually adding the functionality to their config), but we shouldn't encourage it and we should not assume the keymapper is running as the active user.

I'm also not convinced the lunch stuff was ever fully baked anyways, as @RedBearAK will likely totally attest.

**Comment by RedBearAK** [comment]
@joshgoebel 

> will likely totally attest

Yes. Kill it. Kill it with FIRE. 

There has to be a safe, simple and reliable way to launch commands without causing the main process to go on the fritz. 

I suspect no one ever really used `launch` in the default running as root setup. It was just too cumbersome to try and run things with user permissions, and most users would have known that launching things as root was a bad idea. Pull the ripcord.

**Comment by joshgoebel** [comment]
@RedBearAK You should see #44

**Comment by RedBearAK** [comment]
> You should see #44

Yeah, I've been taking a look at that.
