### ISSUE TITLE
(docs/usability) Key.SUPER vs Key.META

### ISSUE THREAD

**Issue by joshgoebel** [joshgoebel/keyszer#5]
Ref: https://github.com/mooz/xkeysnail/issues/158

The names in `key.py` come to us from the kernel, so I'm hesitant to change them but perhaps we should add an alias:

```
LEFT_SUPER = LEFT_META
RIGHT_SUPER = RIGHT_META
```

And then encourage the use of these over the more ambiguous `META` naming?

**Comment by joshgoebel** [comment]
@rbreaves Any thoughts on this one?  Since `LM`, `RM` and `M` are kind of ambiguous (they do NOT map to LEFT_META and RIGHT_META, which are the Super keys) I'm considering removing them from my fork (breaking change)  and replacing them with "RA", "A", "LA"...

I see you use "M" a lot in your config... any thoughts on the usability issues here?

**Comment by joshgoebel** [comment]
I already created a PR to update your config to use `Alt` instead, to remove the ambiguity, but I also wonder your thoughts on Super vs META in general and our naming of the modifiers.

**Comment by rbreaves** [comment]
I’d be happy to ensure conformity w/ the change. When/if I switch over to your fork I will likely bump the version to 1.5 to help indicate breaking changes to those that have customized their config.

**Comment by joshgoebel** [comment]
> I’ve not liked using M either

No one is forcing you to. :-)  Your branch should have `Alt`... the PR I submitted should work without any changes to your xkeysnail. 

c73e5b7

**Comment by rbreaves** [comment]
Ahh I see... yea.. I sorta disagree with naming Meta as Cmd.. in a technical sense that is accurate - BUT in a practical sense that just doesn't translate because on Linux or Windows Ctrl is effectively Cmd even though if you were to remote into a mac clearly mac is using Meta/Super as their Cmd key and not control.

So I don't know, this is your fork, and I get you want to be technically accurate, I just don't know what value that alias has for Linux users in particular vs practicality. I simply go by most used to unused modifiers, 1 - Ctrl/Cmd, 2 - Alt/Alt, 3 - Win/Ctrl and that is how my mental mind map works with it all even though I fully understand the key values themselves on the keyboard, don't work that way and that is what has absolutely tripped everyone up on figuring out how to create a remapper for Linux or Windows to work like a mac lol.

```
Modifier("R_META", aliases = ["RSuper", "RWin", "RCommand", "RCmd", "RMeta"], key = Key.RIGHT_META)
Modifier("L_META", aliases = ["LSuper", "LWin", "LCommand", "LCmd", "LMeta"], key = Key.LEFT_META)
```

**Comment by joshgoebel** [comment]
I'm not sure either of us is fully wrong here, but this is how I think about it.  I look at my keyboard, and it literally has some named keys:

- control
- alt/option
- command

So those are real names that exist in the real world... If I hit the "Command" (literal name) key and some operating system outputs the letter "A" **it's still the Command key I hit** - not the A key.  So there is a difference between the literal name of the key and how it's used by any given OS. 

GTK3 had a name for this concept for a while, "Primary"... on Linux Primary key is Ctrl, on Mac Primary key is Cmd.  Because the key is literally named "Command" (on many keyboards) I personally don't think reusing the name the way you want to conceptually helps the discussion much.

**Comment by joshgoebel** [comment]
And since we're at the lowest level (remember X can still redefine all these keys itself!) I think it makes sense to go with the LITERAL names, not the behavioral names. :)

**Comment by rbreaves** [comment]
> but the above comment is my justification for leaving Cmd in the default alias list for META.

Yea, and I don't blame you for that, I will take into my realm as discussed on that other thread and create an A method to do a translation in the config file I imagine that will yea use the K method ultimately. And that is a good way of wording it were discussing the difference between what's literal and what's behavioral.
