### ISSUE TITLE
Allow YAML config for keymap definitions

### ISSUE THREAD

**Issue by tnyeanderson** [joshgoebel/keyszer#62]
**Is your request related to a specific problem you're having?**
Users should be able to define keymaps in a declarative, readable config file (YAML) rather than an executed python script.

**The solution you'd prefer or feature you'd like to see added...**

Spec (ignore kinto naming): https://github.com/rbreaves/kinto/issues/115#issuecomment-989271331
Example parser: https://gist.github.com/tnyeanderson/23057d8286be5a90ce25923f41352dc8

**Any alternative solutions you considered...**

The linked example gist actually converts the YAML into an xkeysnail/keyszer `config.py` file, which was fine when it was just going to be a translation layer for kinto. But here in the upstream, it would probably be better to read the values from the config file and call the corresponding map functions directly (if possible).

**Additional context...**

rbreaves/kinto#115 has more context and discussion regarding this.

**Comment by joshgoebel** [comment]
Not really interested in this direction, _but this is also exactly WHY the the config is Python_.  Nothing is stopping anyone from doing this today.  This feature does not need to be up-streamed.  Just add code to the config file that loads and parses YAML. 

Someone could write a plugin that does this and then share it... Kinto could decide to do this... that's the power of the Python config.  It allows people to build whatever kind of configs they want... but a YAML config would not permit that.

If someone wrote a plugin and it got WIDE adoption this issue could perhaps be revisited... but I think it's still likely we'd just point people to the plugin reposition rather than have this in core.
