### ISSUE TITLE
Shift key binding issue (Kinto)

### ISSUE THREAD

**Issue by rbreaves** [joshgoebel/keyszer#95]
**bug or unexpected behavior**
In general this may just become a running log of any issues I come across specific to the default Kinto remap and how to resolve them.

**Bug 1**

Shift key not being bound persistently when using bind.

Sorta subtle - to reproduce you just need to repeat up/down in quick succession - like how most coders will likely use it. If you go at it slowly, initially, it will then stick but that is problematic. Needs to stick from the start imo if bind is defined.

Specific remap (for sublime text)
```python
K("Super-Shift-up"): [bind,K("Alt-Shift-up")],       # multi-cursor up
K("Super-Shift-down"): [bind,K("Alt-Shift-down")],   # multi-cursor down
```
log
```bash
(DD)   COMBO: LSuper-LShift-DOWN => [<ComboHint.BIND: 1>, Alt-Shift-DOWN] [Sublime Text]
(DD) spent modifiers [<Key.LEFT_META: 125>, <Key.LEFT_SHIFT: 42>]
(DD) resuspending keys
(DD) suspending keys [LSuper<Key.LEFT_META>, LShift<Key.LEFT_SHIFT>]
(DD) BIND: {<Key.LEFT_META: 125>: <Key.LEFT_ALT: 56>}
(OO) press LEFT_ALT
(OO) press LEFT_SHIFT
(OO) press DOWN
(OO) release DOWN
(OO) release LEFT_SHIFT

(II) in DOWN (release)
(DD) on_key DOWN release
(DD) resuming keys: [<Key.LEFT_META: 125>, <Key.LEFT_SHIFT: 42>]
(OO) press LEFT_SHIFT
```

**setup**

- Python version: 3.10.4
- Keyszer version: 0.6.91
- Kinto version (if applicable): 1.2-13 (e106710)

**Comment by joshgoebel** [comment]
Shift isn't bound at all. Only the first key of the combo is bound. If you want to bind shift make it the first key of the combo.

**Comment by joshgoebel** [comment]
And please one issue per bug is much preferred unless you strongly feel the bug/issues are related.

**Comment by rbreaves** [comment]
Will do. Also I am not sure how I feel about single modifier key binding as I kinda just assumed we'd be binding all modifier keys (unless the user releases a modifier). Perhaps there were technical challenges with that when you created the bind function?

I know I meant to break out the changes I had made to K to its own binding type function, but never did - hence it being dropped in future versions of xkeysnail.

**Comment by rbreaves** [comment]
And yea switching Shift to being first really does nothing, actually breaks it to doing nothing at all.

```bash
K("Super-Shift-up"): [bind,K("Alt-Shift-up")],       # multi-cursor up
K("Super-Shift-down"): [bind,K("Alt-Shift-down")],   # multi-cursor down
```

Like I said bind will either need to fully bind ALL modifier keys or we create a secondary binding function to behave as Kinto will need it to behave.

**Comment by joshgoebel** [comment]
> Also I am not sure how I feel about single modifier key binding

MVP.  It worked great with tab-switching so there was no need to go further.

What did you change?? I was expecing to see:

```
K("Shift-Super-up"): [bind,K("Shift-Alt-up")],       # multi-cursor up
K("Shift-Super-down"): [bind,K("Shift-Alt-down")],   # multi-cursor down
```

> Shift key not being bound persistently when using bind.

I don't find this helpful.  Could you please explain the expected behavior of the keys inside a particular application and the behavior you are seeing instead - so I can test it on my end also?

**Comment by joshgoebel** [comment]
>  In general though I think there's been a misunderstanding between how you and I have envisioned a or the binding function to operate.

Perhaps, but I'd rather say I didn't understand the full scope of the problem... alt-tabbing was the obvious sticky brokenness, so we fixed that - which seemed to only require binding cmd/alt.

And then I imagined we'd solve the problem, until this issue was opened.   So as soon as I can understand and reproduce the issue I can look at what our options are for improving binding. :)

**Comment by joshgoebel** [comment]
I'm on and off but if you wanted to join our Discord: https://discord.gg/emneQKeN

**Comment by rbreaves** [comment]
Sounds good - I will try and review the area of your code that handles the binding here after lunch and see if there are any simple or elegant changes that can be made.

I will also mention your original thread and I apologize I was not more active at the time you were @'ing me in that thread as I am sure it would have helped while you were creating it. But like is often the case when we making remappers - we can only be aware of the key maps that directly impact us (and Kinto was largely made with Sublime Text and VSCode in mind and providing full coverage for those apps as well as the terminal.).

https://github.com/joshgoebel/keyszer/issues/11

**Comment by joshgoebel** [comment]
It may be sufficient to update `auto_sticky` and augment/improve `simple_sticky`... the inside portion should be refactored out into a function that does the setup for a single sticky pair of keys, then we could loop over a larger set of paired modifiers (rather than just the first).

But I'm not yet certain this is necessary - I don't think it's related to our current Sublime problem at all.
