### ISSUE TITLE
Hiding input key from app without suspend? 

### ISSUE THREAD

**Issue by RedBearAK** [joshgoebel/keyszer#98]
@joshgoebel 

I've had my menu bar turned off completely in VSCode, so it hasn't been causing me problems. I just turned it back on and realized it doesn't play well with the Option key scheme. This is caused by my suspend timeout still needing to be set to 0.1s due to the touchpad Modifier+click issue. So unless I'm super fast the app will always "see" the Alt key press, and the menu will steal the focus. 

So I'm wondering if there isn't some more deliberate way to "hide" the Alt key in the Option key scheme shortcuts from the app, so that they don't constantly activate menu items in an app with menus that respond to the Alt key.

**Comment by joshgoebel** [comment]
How?  This is what suspend does?  Only two choices. Suspend the keys or pass them to output...

**Comment by RedBearAK** [comment]
> How? This is what suspend does? Only two choices. Suspend the keys or pass them to output...

No idea. A special longer suspend directly attached to each of these shortcuts? A custom version of `combo`? 

I don't really know what's possible.

**Comment by RedBearAK** [comment]
Finally found a solution for VSCode to stop activating the menu with Alt. 

```json
    "window.titleBarStyle": "custom",
    "window.enableMenuBarMnemonics": false,
    "window.customMenuBarAltFocus": false,
```

I had the second two lines in the user settings.json file, but not the first. That seems to be key to making it work. 

But this is just a solution for this one specific app with a menu bar.

**Comment by joshgoebel** [comment]
By definition "suspend" is what I call hiding input from an app... so this issue (as worded) makes zero sense to me... when a key is pressed there are only two choices - send it to the OS or suspend it - again by the definition we use.

_Well, I suppose a 3rd option would be to drop it, but one can already do that with a conditional keymap..._

Since we can't (very well, or at all) predict the future - it seems sometimes we're going to be wrong - hence the current default suspension policy of waiting 1s for further input.

I'll leave this open for discussion but someone needs to have a really bright idea... I think mine was pretty bright (other than the mouse/trackpad issue)...  and I continue to use mine with kb + mouse going thru keyszer with no issues.

**Comment by RedBearAK** [comment]
> (other than the mouse/trackpad issue)

Which can't be avoided on laptops in general, unless you use an external mouse. 

So the fundamental problem is that I have to have modifiers generally "unsuspend" quickly enough that Mod+clicking on a touchpad actually works like it's supposed to. But with these specific shortcuts I need the suspend to stay in place for longer. Is adding something like a "suspend_mod(1)" flag to the input combo already too late to catch the Alt key press that the app would "see" when I just press the Alt key in the first place, before completing the entire combo? 

Is what I'm thinking about basically impossible if the initial suspend timer was already allowed to time out, due to being too short to "carry over" into a longer secondary suspension for a specific combo?

**Comment by joshgoebel** [comment]
> Which can't be avoided on laptops in general,

Because of the trackpad? Yes, then you'd need to turn the timeouts down to allow you to combo click using the trackpad.

> I have to have modifiers generally "unsuspend" _quickly enough_ that Mod+clicking on a touchpad actually works like it's supposed to.

But that's too quick for general usage IME.

> But with these specific shortcuts I need the suspend to stay in place for longer.

We don't know what shortcut you're going for until all the keys are pressed - we don't know the future.  So I'm not sure I follow.

Perhaps it would help if you wrote out an example step-by-step of how it'd work both in a suspend and non-suspend scenario and how the system would make the correct decisions.

**Comment by joshgoebel** [comment]
I'm also less interested in solving a fraction of the problem vs the whole problem... I think I hear "make Alt suspend longer" if I'm listening carefully, BUT that only solves Alt, not Super - which (for many setups) has the exact same false-trigger behavior.  And one can imagine other combo keys perhaps having the same issue on special setups - even if Alt and Super are the most complained about.

**Comment by RedBearAK** [comment]
> I'm also less interested in solving a fraction of the problem vs the whole problem... I think I hear "make Alt suspend longer" if I'm listening carefully, BUT that only solves Alt, not Super - which (for many setups) has the exact same false-trigger behavior. And one can imagine other combo keys perhaps having the same issue on different setups - even if Alt and Super are the most common culprits.

Yes, I was thinking about Alt primarily due to it being such a problem with most any app that still has a menu bar that responds to Alt. The Super key by itself in my experience is mainly used to activate app menus and overviews, and that can be disabled in a central location. But I can imagine there are other places where Super can misbehave, I guess.

**Comment by joshgoebel** [comment]
> and that can be disabled in a central location

Except I'm not that interested in telling people "you need to reconfigure stuff first"... that's Kinto's thing - (and that's fine) -  that's not a thing I want to embrace at the Keyzer level though - this assumption that someone first has to tune their system to get optimal results...

I'd rather say "it depends vastly on your system and goals"...

If suspension was per-key you could play around with the timers, but the first person who wants to alt-click anything just breaks it all over again... and I want to be open-minded to such things (users have the power) - not base my decisions on some pie in the sky "default linux desktop", because I think the whole concept is a little ridiculous. :-)

Again, I love that Kinto is trying to tackle the problem at that level... but we're at a lower level.

**Comment by joshgoebel** [comment]
> If suspension was per-key

If someone wanted to play with this and it turned out to be SIMPLER, that'd be an interesting PR to review, but it's not very high on my priority list as right now suspending (and resuming) all keys at once seems easier/less complex.

**Comment by RedBearAK** [comment]
Custom menu bar in VSCode(s) pretty much cures the reason I was asking for this, so no reason to hold it open. Closing.
